---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1tus3yyjzg5ehrzxf32nwnqatrmk7pput2s2gqshjuyh52phwx3mqrdkqez"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1tus3yyjzg5ehrzxf32nwnqatrmk7pput2s2gqshjuyh52phwx3mqrdkqez"
