apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:wL3oQOd4wSHg/ybim0jku/m3Rj5rB8YPDDNL3rJ0T0HnZPB0,iv:GFc7pOTnG8j/7uiFYMWBgV24wssPyeJKqr8/Q/rZXQA=,tag:fhgE0VRgNBfvPZvnJt0m/Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:QaXRHihtwtSyj6l8xcwW757HsMFMxNAu+lzBL79Ogx9fPKklKd1/ojXUfzO+835qerGV71JbryMUux5kglDxngSUpWqhlNB3sMU5qF4luEcQoKB9DYEHW90t8uVM8QEP+rFL9h/SvW9fJNvBOFnSzrZX2F43wJUszN3V0CRHkm1bSpBdnHKjFf76U5bkBso6epJcotyFew6mSNmlxBFvJfYMdkOn44ImYzZw3zYfMw==,iv:qm9RU0uZucaBbCGBEbdwaIpEWbkeaiLDI3Y2ILVKSf0=,tag:msWnCyujxg+qRIS/vGPBCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tus3yyjzg5ehrzxf32nwnqatrmk7pput2s2gqshjuyh52phwx3mqrdkqez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJa2dVUFYvZ2d5eU0xL0xz
            MzVOb2hhNlVNS2pXbXJFOTVuS0swWXJnL2lBClJUSjZDelF4QWpiVUgzVmtOd1Vx
            U29ub0ZKUFBxTHdidG8yaVZJTjFvUGcKLS0tIHduN09SOG1Jb0piYW82Znk5Q1pi
            UmdJLy9TdTVUaUM5MlBBZjNReXJKRUkKQ2aDcZ8e11sXaV2yZCiGi7trDRpYznue
            VU9Xy3IcSRoromP4LZKLSi5MKhNUS/rYUJBwcN2EL9ldx5ck8NQHKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-19T22:47:50Z"
    mac: ENC[AES256_GCM,data:eSrVA2b2LyAQeh0/g5mxanjfKeC/mhBRpQjTL4M0PX0n69bfnikRv/GFsMaiSMUIPLCMIcShmLcLYu93JlSiSxQLjmGHEKYM26mOAr/OMTSNROOnSF+rdGz2NcUFi2xtGDrivU4H3rM2pQi7IUpw4uQ3wcQOZYWSQCMRoZWJOK0=,iv:yREemcytS0EOwY0yOMd3gf5msd0l+r9vNTkfiozahWo=,tag:qVKJaivLFmw2ZE0PsZH/gg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
