apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:UY7meXCJqPo7JXbYQifMFJaZUjvjH5hS8pEcx+RAVISqTftF,iv:4SFAZt6vINxLV3jnlYy/6ZEIALnFV01OVphINjPw/YQ=,tag:Bi87tJRd9XHg7/F5N6i2Rw==,type:str]
    credentials.json: ENC[AES256_GCM,data:F5PobfD9QuP2+wtFT+zQeZ/e2J5cSNEDm5ye9X4/VcPfI0cFrGJcUOCtCmanPWHT6U7SqL6qHfkah06mEicPqQ3ByFFamOWT8w3BkjwG3w1TqgoGKvN14OG8U8CPzUOOMIHHP/q1n9U4jBdVDPh/trMxI7QtMdJTLSNsWQK7YGkwuHrJak6X6QnP9BsFcaLggZTXp27jxJqXVFWEnZAFHhEi1dWdBXWavH5znKHDuQ==,iv:Ky+qsLZkAeP6SgB4QS/3gb6f7oFEYA4WlN00pJ/bo4k=,tag:UUSnSDTzWvBnWDy3Y+2q7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tus3yyjzg5ehrzxf32nwnqatrmk7pput2s2gqshjuyh52phwx3mqrdkqez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrOHhKWStXZEZsZjlQc0ZS
            cmp1WU05NHVXR00xRG1SM2I1dmhyRGVsOWo0CkxIWWFXakZYdlVFYzJmK1NSNEVi
            MEg1Uy9ralR0b3VMRXkyNGFqYlZtYjgKLS0tIDJwL0dFU1lYNnpRb2hES1ZGN2R6
            SUxrbmJNOXFBaVoxb2VXTFoxQXIySUEKmhkSJN4WylCZ08EBQD2Z1yb/Tte37l/K
            BZVUieyfC2Lp82xfgeekDBYoR0mweq7DMCZdz4LkJFzFoACBGp3ibA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-06T19:11:13Z"
    mac: ENC[AES256_GCM,data:jquQQP/XMyltN7ZGfeNGKz0xNAkj9sLdd43Y2h8k58IwnS1H8rFpURYQKALPNOLzuF9d53I0dvOByUuy23BJMHxxS/H9wO7e0qNIZwzPsfyd4kPVDncmtlCcET2eOSrqW2MM5GfS7FduYN7glL9J3fb5l3ptMDlffKk8NBSqIwI=,iv:idZologe4t5W8b/2xhcLgIT+RXiQM4K39ngklB2cQk4=,tag:75zep00vbeLDkPJ9SHTXLw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
