apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:hsynv+prdq7IIBXIj1auCm+n55YSw4zZh+0DZ/ROYYqJ9hMYbrEHrg==,iv:gxNcmKUD6bFdztkSvGNknkTEwBcnMLVi089HIwmGjO8=,tag:vXAXBaqT61r1TO9iQ3DtUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tus3yyjzg5ehrzxf32nwnqatrmk7pput2s2gqshjuyh52phwx3mqrdkqez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwOG9aaTF6czllcGdHeWRT
            SjJpRS9GRjR4b3NlcE1wRVJBNWQ2SDF4UFJJClliWHQ0WmVJOHVpdXpXa09pRC9J
            cGxBNGJ0bTVka1FmTkNoeXRibHpCemMKLS0tIFFNUE5VQVl5ZmpBeE1lb0VCT3BM
            dEtubzFRaFEwUnpKbFR5TmlmL3NFOVkK+4Ul9w33ZGU2rLTFSrjGdVWpz2N3WQ6G
            5eBd7epT5JfH3IWDOXAbfXbK8Y3dr30bMlScqrC7mBYfXDWpVP86gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-19T22:47:50Z"
    mac: ENC[AES256_GCM,data:hi1BluECijkF+tEhmsKb4IvBZgAGDcvUiEAzUf7/tPjBf6rAKcgWzb6aCJNVMPnadjykAxofVbHeP0ODb8v/0P7QZTrjYnRUgJaeiubIsj8A0WjbdAwncXUTpWlPgYse/DKabwBAJB09ItMYubscz+ykpKYFfoRHO6lqfRQSCyw=,iv:1TB60Y6QpBehyvHGOpc3NCZ+liks/tOS0M2d/7jaBvY=,tag:v7xlgDJ/5IRzbm/h0NmIng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
