apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:c0omKcEomwhT9xWLvNlFWtsH1t0WFDxVPFsYXmsL17u35Jq8IG5J4g==,iv:IgeMNrZ4S4x3S5DO2clbZp1ywLTxGgs50jakkcOEP7o=,tag:h1pcy+AHV7RM2xPnQ8c8Cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tus3yyjzg5ehrzxf32nwnqatrmk7pput2s2gqshjuyh52phwx3mqrdkqez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTUsxVWxFUzExaWZpSUUx
            UzhabjlnMS8rcGJJMXBZZmdjdWVaOWxQOUJJCk01WnJIMUpjSnBCZ0pQRzhjMkV5
            L0lZRkFPTEEzUGs4d3pZOXlSR3I2Y3cKLS0tIEtvaWtoVFF5TVFSOGY5Wnc0LzI5
            UG4rbE1WV1BheTY5UGt1Q2JuZmhoK1EKJ8jUVHH9jI0n/sUY1FvMMy7o+m79ZqD5
            Pv4bFLz8VhXts9C0Rj1TiHwzEv37XxDN4heb7BS+9mLNmpWibQsdrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-19T15:10:10Z"
    mac: ENC[AES256_GCM,data:e8wXM8shw3LaUjLgca4nY2RttKGshSqMxJkY8tWqdJfw8OqChE249sypFi+Vi4muQuvpLN00Dnm9X4yFnHduFcrdn0+T7b52FD8d3UeuWaw6Vk+eR7M7zE1Njccd4Lj2nZj2xfY3RSR1hgGb7swemdgSI7P7PKDopbl3XCqbXsQ=,iv:SwE/sazpyz1GqWv24VuFOXpVUtUISKr/Ux3At39O9J4=,tag:t7eWUoU0gkzW/XbgtZQrSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
