---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Rome"
  CLUSTER_CIDR: "10.69.0.0/16"
  NODE_CIDR: "10.50.50.0/24"
  BGP_ADVERTISED_CIDR: "172.24.10.0/24"
