apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:HAyIWagY/Ft9U4Kg9DafvuPiBa6cjFlcQlabuhrfzlw=,iv:+YQQ5/ZRJamU49SHLEdeRN0BeSYZopIcIqOBAQA5PEM=,tag:r1O9DIabiKfBSZZrimriMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tus3yyjzg5ehrzxf32nwnqatrmk7pput2s2gqshjuyh52phwx3mqrdkqez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZbUdXd1JXbkdOUmEyZG5l
            NGxra2c4OGt2U2I0TG5Qcnd0TzdVVC9GSXdVCmpVZ2xIbTg4SUIyVjVsRktCbzlV
            V2tuN1FTeTRHcjkyaEcvMVF2MlB3QTgKLS0tIFRQblpnVnZUYmFIWnVacWw5d010
            ei9tQy8zb1JtUzAyRU0wcVVSSklsWXcKX1uj3F3/Gfi/3E+TtXhfU3E3KpuHun/J
            Zjvw+UkTSyvzPPchwaZU7hx6FcLMb/0jfrjxsi/adwcdGE6Uv+hotQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-19T15:10:10Z"
    mac: ENC[AES256_GCM,data:JNKbfq1+hjngtJhRRraG/v5pJfGlVQe4LcIVu7J6G/AICVwC4LeYIlohyZdsbivOfchWQxDzAh0p68e8WSSzEfo4KMIxU/6kI657xEUST+SL9WfNYGBCa4RQUUiVSf6/iOUU7jcR26gWNcE8HwAOACRoJKEsJqF1r4VfPWOXxwo=,iv:boqFA6UE+Z0DstauGeJrlzGnoe4AY/C4S0yGZAmKF0o=,tag:nYTvtFaroqA9ZDYGjKQCLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
