apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:/Pwu9y54uhzYFuh5vZEaa2m/qSCR3PjSMEN7hBzOpMg=,iv:URUtJWj5OmmutCJk6FJYzE1VFfVAVAl/GQxRow5a0MI=,tag:ewzNpR0HHls5vQGjfhNnaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tus3yyjzg5ehrzxf32nwnqatrmk7pput2s2gqshjuyh52phwx3mqrdkqez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudG14VjZCNHdvcmI2UWlD
            OVFxZEpDd3VKa0lmQUFaQmVlc3dNRDlHeGlzCnRySnZrOTVwRC9Bc1BRcjhaZFZN
            ZUgxbHB5SXBvMFUzd3pyZzNUcnVqOEEKLS0tIFdzQUExSHpQcnZuc3ZJUVJCQmRx
            T0tTZGQyblArYXN5bFk4NG9MSVkyQk0K5uKhcrZMNSSNqHnkBe7iO0hhQFQ/aEXV
            91898KHRK242FzqAAa9QO0xmpR3OlgAHqgZrA4AK9W0ph+AexQuIZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-19T22:47:50Z"
    mac: ENC[AES256_GCM,data:8RgzRatQ/yhOIgsaoewcVZmrndyV3JVcJ4FF4veOWrS0SqB8brnwikz4uqI3tcQx/coxaw1iRvq5g/rxjfpZbtbUSYc2jYQixFjbgSp/GalIwQ0TP9RWqUvav7Ct/jkjQ5+9HiWXW7iyJj0nKS/zp3Eo2RCz3ZFWiILMV549u50=,iv:uW05pufIrh0NhysV4nzZiG3hUNWG5IsYeIfiaodauVg=,tag:WhArgtJqJvzoQvoRnpHZog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
